version: '3.8'

services:
  tiger-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001/api
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - tiger-backend
    networks:
      - tiger-network

  tiger-backend:
    image: tiger-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://username:password@postgres:5432/tiger_db
      - JWT_SECRET=your-jwt-secret-here
    depends_on:
      - postgres
    networks:
      - tiger-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tiger_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tiger-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tiger-network

volumes:
  postgres_data:
  redis_data:

networks:
  tiger-network:
    driver: bridge

