'use client';

import { useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { EmojiSelection } from '@/types';
import { Download, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface MoodCardCanvasProps {
  selectedEmojis: EmojiSelection[];
  whisper: string;
  reminder: string;
  category?: 'mindful' | 'tiger-linked' | 'trendy' | null;
  onSave?: (imageData: string) => void;
  onShare?: (imageData: string) => void;
}

export function MoodCardCanvas({ 
  selectedEmojis, 
  whisper, 
  reminder, 
  category,
  onSave, 
  onShare 
}: MoodCardCanvasProps) {
  const canvasRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const generateImage = async () => {
    if (!canvasRef.current) return;

    setIsGenerating(true);
    try {
      const canvas = await html2canvas(canvasRef.current, {
        backgroundColor: null,
        scale: 2,
        useCORS: true,
        allowTaint: true
      });
      
      const imageData = canvas.toDataURL('image/png');
      
      if (onSave) {
        onSave(imageData);
      }
      
      return imageData;
    } catch (error) {
      console.error('Error generating image:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    const imageData = await generateImage();
    if (imageData) {
      const link = document.createElement('a');
      link.download = `mood-card-${Date.now()}.png`;
      link.href = imageData;
      link.click();
    }
  };

  const handleShare = async () => {
    const imageData = await generateImage();
    if (imageData && onShare) {
      onShare(imageData);
    }
  };

  const getCategoryColor = () => {
    switch (category) {
      case 'mindful':
        return 'from-green-400 to-emerald-500';
      case 'tiger-linked':
        return 'from-orange-400 to-amber-500';
      case 'trendy':
        return 'from-blue-400 to-cyan-500';
      default:
        return 'from-purple-400 to-pink-500';
    }
  };

  const getCategoryLabel = () => {
    switch (category) {
      case 'mindful':
        return 'Mindful & Touching';
      case 'tiger-linked':
        return 'Tiger-linked';
      case 'trendy':
        return 'Trendy & Playful';
      default:
        return 'Custom Mood';
    }
  };

  return (
    <div className="space-y-4">
      {/* Mood Card Canvas */}
      <div
        ref={canvasRef}
        className="relative bg-gradient-to-br from-white to-gray-50 rounded-2xl p-8 shadow-xl border border-gray-200 min-h-[400px]"
      >
        {/* Category Badge */}
        {category && (
          <div className={`absolute top-4 right-4 px-3 py-1 rounded-full bg-gradient-to-r ${getCategoryColor()} text-white text-xs font-medium`}>
            {getCategoryLabel()}
          </div>
        )}

        {/* Emojis */}
        <div className="flex justify-center space-x-4 mb-8">
          {selectedEmojis.map((emoji, index) => (
            <div
              key={emoji.id}
              className="text-6xl animate-bounce"
              style={{ animationDelay: `${index * 0.2}s` }}
            >
              {emoji.emoji}
            </div>
          ))}
        </div>

        {/* Whisper */}
        <div className="text-center mb-8">
          <h3 className="text-lg font-semibold text-gray-700 mb-4">Whisper</h3>
          <p className="text-gray-600 leading-relaxed italic">
            "{whisper}"
          </p>
        </div>

        {/* Divider */}
        <div className="w-full h-px bg-gradient-to-r from-transparent via-gray-300 to-transparent mb-8" />

        {/* Reminder */}
        <div className="text-center">
          <h3 className="text-lg font-semibold text-gray-700 mb-4">Reminder</h3>
          <p className="text-gray-600 leading-relaxed">
            {reminder}
          </p>
        </div>

        {/* Footer */}
        <div className="absolute bottom-4 left-4 right-4 text-center">
          <p className="text-xs text-gray-400">
            Generated by Tiger • {new Date().toLocaleDateString('vi-VN')}
          </p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-3">
        <Button
          onClick={handleDownload}
          disabled={isGenerating}
          className="flex-1 bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white font-medium py-2 rounded-lg shadow-lg hover:shadow-xl transition-all duration-300"
        >
          <Download className="w-4 h-4 mr-2" />
          {isGenerating ? 'Đang tạo...' : 'Tải xuống'}
        </Button>
        
        <Button
          onClick={handleShare}
          disabled={isGenerating}
          variant="outline"
          className="px-6 py-2 rounded-lg border-2 border-gray-300 text-gray-600 hover:bg-gray-50 transition-colors"
        >
          <Share2 className="w-4 h-4 mr-2" />
          Chia sẻ
        </Button>
      </div>
    </div>
  );
}